### ISSUE TITLE
feat: add support for TTL on states

### ISSUE THREAD

**Issue by rolandjitsu** [infinyon/sdf-support#1]
There are scenarios when users may need to keep a state outside of a window, e.g.:

```yaml
apiVersion: 0.6.0

meta:
  name: some-sdf
  version: 0.1.0
  namespace: company-inc

config:
  converter: json
  consumer:
    default_starting_offset:
      value: 0
      position: End

types:
  some-event:
    type: object
    properties:
      foo:
        type: string

topics:
  some-events:
    schema:
      value:
        type: some-event

services:
  track-something:
    sources:
      - type: topic
         id: some-events
    states:
      some-records:
        type: keyed-state
        properties:
          key:
            type: string
          value:
            type: arrow-row
            properties:
              timestamp:
                type: i64
              foo:
                type: string
    partition:
      assign-key:
        run: |
          fn key_for_evt(evt: SomeEvent) -> Result<String> {
            Ok(evt.foo)
          }
      update-state:
        run: |
          fn update_record(evt: SomeEvent) -> Result<()> {
            let mut record = some_records();
            record.foo = evt.foo;
            record.update()?;
            Ok(())
          }
```

In this case, the state will keep growing until the process may run out of memory.

It would be helpful to add support for a `ttl` on the state which would instruct the worker to cleanup records that are older than `ttl`. E.g.:

```yaml
states:
  some-records:
    type: keyed-state
    ttl: 24h # After 24 hours, remove any record that is >= 24 hrs
    properties:
      key:
        type: string
        value:
          type: arrow-row
          properties:
            timestamp:
              type: i64
            foo:
              type: string
```

Alternatively, removing everything after `ttl` may also be an option, but users may need to keep recent data in the state for whatever purposes.
