### ISSUE TITLE
feat: add support for using intervals in schedules

### ISSUE THREAD

**Issue by rolandjitsu** [infinyon/sdf-support#4]
Currently, when using [schedules](https://www.fluvio.io/sdf/how-to/scheduling), we can only use cron notation to run services. This limits running logic more frequently than a minute.

It would be great to support an `interval` property so that we can run logic at higher frequency:

```yaml
schedule:
  every-min:
    # cron: "* * * * *"
    interval: 30s
```
